server:
  port: 8080

#公众号配置
wechat:
  appId: 测试号appId
  appSecret: 测试号appsecret
  tempId: 天气测试模板id
  drinkTempId: 喝水提示模板id
  offDutyTempId: 下班提示模板id
  myBirthday:  自己的生日 yyyy-MM-dd
  babyBirthday: 对象生日
  loveDay: 纪念日


#彩虹屁接口
tianapi:
  appKey: 天行数据api的apiKey
  area: 天气城市
