server:
  port: 8080

#公众号配置
wechat:
  appId: wx302b3d5f27936755
  appSecret: 451067fc7f78b276df7417e3fb9c1e2b
  tempId: ij7ApDQMvyBBX_AovMlEiIZlOM8ZGPZtOWvnr0r8PwI
  drinkTempId: 5Lu9llWjU5qJ25j9RY5owQu5pWjn5T3xUT4j150OqPY
  offDutyTempId: 6uknFmzaD8i0Th2eLUMJLR1V2lcsvfYEPogV0gCPvLU
  myBirthday: 1995-05-22
  babyBirthday: 1997-02-09
  loveDay: 2015-11-11


#彩虹屁接口
tianapi:
  appKey: af3e574aeb5372bae5be9d18690cdc91
  area: 北京
