server:
  port: 8080

#公众号配置
wechat:
  appId: 测试号的appID
  appSecret: 测试号的appSecret
  tempId: 测试号的模板id
  myBirthday: 自己的生日(1998-10-16)
  babyBirthday: 女朋友的生日
  loveDay: 相恋的日子

#彩虹屁接口
tianapi:
  appKey: 天行数据Api的apiKey
  area: 要获取天气的城市
